### ISSUE TITLE
Can I sort the colums on the soldering order?

### ISSUE THREAD

**Issue by liubenyuan** [pioupus/KicadSolderTool#7]
It would be much better if I can sort the columns on the soldering order.

For example, I want to solder all 0R first, or I can sort the R* (resistors) first, where each Rs are sorted by their corresponding values, and then C*.

**Comment by pioupus** [comment]
I changed something in the sorting mechanism. Dont know if it helps but now the sorting order is footprint size, value, reference.
When I solder my PCBs I always solder complicated / small footprints first. Therefore I keep the footprint size at higher sorting priority

**Comment by liubenyuan** [comment]
Thanks. I want to put the components on solder pad manually and using heat flow to solder them on. I think the default order is ok with me.
